<a href="https://colab.research.google.com/github/ShiaHp/DACS4_RecSystem/blob/main/rcm_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
ratings = pd.read_csv("/content/UserAnimeList.csv")
animes = pd.read_csv("/content/anime_cleaned.csv")
ratings = pd.merge(animes,ratings)
ratings

,anime_id,title,username,my_score
0,11013,Inu x Boku SS,karthiga,8
1,11013,Inu x Boku SS,RedvelvetDaisuki,0
2,11013,Inu x Boku SS,shuzzable,0
3,11013,Inu x Boku SS,sprite1989,0
4,11013,Inu x Boku SS,thetreedude,7
...,...,...,...,...
962918,37405,Dokidoki Little Ooyasan,purplepinapples,0
962919,37886,Wo Shi Jiang Xiaobai (2018),purplepinapples,0
962920,37255,Genki Genki Non-tan: Obake Mura Meiro,purplepinapples,0
962921,35229,Mr. Men Little Miss,purplepinapples,4
962922,36315,Mushi Mushi Mura no Nakama-tachi: Minna Ii Tok...,purplepinapples,0

In [ ]:
user_ratings = ratings .pivot_table(index = ['username'], columns = ['title'], values='my_score')
user_ratings.head()

title,"""Bungaku Shoujo"" Kyou no Oyatsu: Hatsukoi","""Bungaku Shoujo"" Memoire","""Bungaku Shoujo"" Movie","""Eikou Naki Tensai-tachi"" Kara no Monogatari","""Eiyuu"" Kaitai","""Parade"" de Satie",.hack//G.U. Returner,.hack//Gift,.hack//Intermezzo,.hack//Liminality,...,ef: A Tale of Memories. - Recollections,gdMen,iDOLM@STER Xenoglossia,s.CRY.ed,the FLY BanD!,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Shunmuki,Ä“lDLIVE
username,,,,,,,,,,,,,,,,,,,,,
#NAME?,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.0,5.0,6.0,...,0.0,NaN,NaN,NaN,NaN,9.0,9.0,8.0,9.0,NaN
-Dementhia-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
-OoKaMi-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
-RedGoddess-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Shimizu-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
user_ratings = user_ratings.dropna(thresh = 10,axis = 1).fillna(0)
user_ratings

In [ ]:
item_similarity_df = user_ratings.corr(method = "pearson")

In [ ]:
def get_similar_movies(movie_name,user_rating):
  similar_score  = item_similarity_df[movie_name] * (user_rating - 2.5)
  similar_score = similar_score.sort_values(ascending=False)

  return similar_score

In [14]:
lover = [("Love Live! School Idol Project",10),("Naruto",2)]

similar_movies = pd.DataFrame()

for movie,rating in lover:
  similar_movies  = similar_movies.append(get_similar_movies(movie,rating), ignore_index = True)
  
similar_movies.head()
similar_movies.sum().sort_values(ascending=False)

Love Live! School Idol Project               7.486054
Love Live! School Idol Project 2nd Season    6.011822
Love Live! Sunshine!!                        4.193124
Love Live! The School Idol Movie             4.038708
Love Live! School Idol Project OVA           3.373860
                                               ...
Bleach: The Sealed Sword Frenzy             -0.340622
Peace Maker Kurogane                        -0.349885
X                                           -0.356038
Samurai Deeper Kyou                         -0.364505
Tenshi Kinryouku                            -0.394121
Length: 5185, dtype: float64

# Má»¥c má»›i